# most personal metadata can be found in ./resume.json

- description: Portfolio of web &amp; ui designer/developer hybrid Sean Mahoney, aka {TechnoSheen}.
  img: ../src/images/twitter-card.png

  availability:
    status: true
    available: '👔 Available for new projects. <a href="mailto:sean@technosheen.com">Let’s talk</a>!'
    unavailable: Not available for new projects.

  # Footer actions
  gpg: https://technosheen.com/pub.gpg
  addressbook: /matthias-kretschmann.vcf
  bugs: https://github.com/kremalicious/portfolio/issues/new

  typekitID: dtg3zui

  # Analytics tools
  matomoUrl: https://analytics.kremalicious.com
  matomoSite: 2

  allowedHosts:
    - matthiaskretschmann.com
    - beta.matthiaskretschmann.com
    - localhost
